### ISSUE TITLE
激励视频注册的回调不会触发，大佬还维护吗？

### ISSUE THREAD

**Issue by AlingChen** [mayunyi/react-native-brayant-ad#4]

**Comment by mayunyi** [comment]
维护的

**Comment by mayunyi** [comment]
有错误信息吗

**Comment by AlingChen** [comment]
> 有错误信息吗

看了下源码是注册的事件名称和调用不一致
`return (listenerCache[type] = eventEmitter.addListener(
        'RewardVideo-' + type,
        (event: any) => {
          callback(event);
        }
      ));`
` private static final String TAG = "RewardVideoModule";
public static void sendEvent(String eventName, @Nullable WritableMap params) {
    mContext
      .getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter.class)
      .emit(TAG + "-" + eventName, params);
  }`
